import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import { createCarpoolAvailability } from '../../carpool-availability.js';
import { createPassengerRequestAlerts } from '../../passenger-request-alerts.js';
import { initClientHome } from '../../client-home.js';
import { initCarpoolWork } from '../../carpool-work.js';
const dom=new JSDOM(await readFile('../../index.html','utf8'),{url:'https://example.test/',pretendToBeVisual:true});
for(const key of ['window','document','MutationObserver','HTMLElement'])globalThis[key]=key==='window'?dom.window:dom.window[key];
window.scrollTo=()=>{};window.HTMLElement.prototype.scrollIntoView=()=>{};
const flush=()=>new Promise(resolve=>setTimeout(resolve,0)), stamp=ms=>({seconds:ms/1000}), now=Date.now();
let emit,fail,auth;const store=createCarpoolAvailability();
const api={user:async()=>({uid:'client'}),onUser(cb){auth=cb;cb({uid:'client'});return()=>{};},ready:async()=>true,watchAvailableTrips(cb,error){emit=cb;fail=error;return()=>{};}};
let opened;window.bookingScreen={openCarpool:(...args)=>{opened=args;}};
initClientHome({availabilityStore:store});await store.start(api);await flush();
const card=document.querySelector('[data-home-carpool-open]'),badge=card.querySelector('[data-carpool-available-count]');
const trip={id:'t1',status:'open',availableSeats:2,departureAt:stamp(now+600000)};
emit([trip],{fromCache:true});assert.equal(badge.hidden,true,'cached rows do not claim live availability');
emit([trip,{...trip,id:'full',availableSeats:0},{...trip,id:'past',departureAt:stamp(now-1)},{...trip,id:'closed',status:'closed'}]);
assert.equal(badge.textContent,'1 рейс');assert.ok(card.classList.contains('home-intercity-pulse'));
card.dispatchEvent(new window.Event('animationend'));emit([trip]);assert.equal(card.classList.contains('home-intercity-pulse'),false,'ordinary update does not pulse again');
emit([trip,{...trip,id:'t2'}]);assert.equal(badge.textContent,'2 рейса');assert.ok(card.classList.contains('home-intercity-pulse'));
card.click();assert.deepEqual(opened,['','',true]);assert.equal(card.classList.contains('home-intercity-pulse'),false);
fail();assert.equal(badge.hidden,true);assert.equal(card.classList.contains('home-intercity-available'),false);assert.match(card.textContent,/Не удалось обновить/);
const old=emit;auth(null);old([trip]);assert.equal(badge.hidden,true);store.destroy();

let demand,visible=true,stopped=0;const signals=[];
const alertsApi={hubReady:async()=>true,watchRequestAlerts(cb){demand=cb;return()=>{stopped++;};}};
const makeAlerts=()=>createPassengerRequestAlerts({api:alertsApi,onAlert:data=>signals.push(data),now:()=>now,storage:window.sessionStorage,visible:()=>visible});
let alerts=makeAlerts();await alerts.setContext({uid:'driver'},true);
const request={id:'old',status:'open',createdAt:stamp(now-1000),departureAt:stamp(now+600000)};
demand([request],{fromCache:true});demand([request]);assert.equal(signals.length,0,'initial list is silent');
const added={...request,id:'new'};demand([request,added]);assert.equal(signals.length,1);
assert.equal(alerts.receive({requestId:'new',createdAt:now-1000}),false,'FCM and realtime share deduplication');
alerts.destroy();alerts=makeAlerts();await alerts.setContext({uid:'driver'},true);assert.equal(alerts.receive({requestId:'new',createdAt:now-1000}),false,'reload remains silent for the same request');
demand([]);visible=false;demand([{...request,id:'background'}]);assert.equal(signals.length,1,'hidden page leaves sound to background push');visible=true;
assert.equal(alerts.receive({requestId:'too-old',createdAt:now-400000}),false);
const late=demand;await alerts.setContext(null,false);late([{...request,id:'late'}]);assert.equal(alerts.receive({requestId:'late',createdAt:now}),false);assert.equal(signals.length,1);assert.ok(stopped>0);alerts.destroy();

let targetNext;const host=document.createElement('section');document.body.append(host);
const work=initCarpoolWork(host,{ready:async()=>true,simpleJourneyReady:async()=>true,hubReady:async()=>true,watchDriverTrips(_uid,cb){cb([]);return()=>{};},watchRequests(_count,cb){cb([]);return()=>{};},watchRequest(id,cb){assert.equal(id,'target');targetNext=cb;cb({...request,id:'target',fromCity:'А',toCity:'Б',seats:1});return()=>{};}});
await work.setContext({uid:'driver'},{status:'active',carpoolEnabled:true});work.openRequests('target');await flush();
assert.equal(document.activeElement.dataset.requestId,'target','deep link reaches a request outside the first page');
targetNext({...request,id:'target',status:'cancelled'});assert.equal(host.querySelector('[data-request-id="target"]'),null);assert.match(host.textContent,/закрыта/);
work.destroy();dom.window.close();console.log('PASS: live count, limited pulse, cache/error states, demand audio deduplication, logout and direct request navigation');
