import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import { initBookingScreen } from '../../booking-screen.js';

const html = await readFile(new URL('../../index.html', import.meta.url), 'utf8');
const dom = new JSDOM(html, { url:'https://example.test/', pretendToBeVisual:true });
for (const key of ['window','document','MutationObserver','Option','HTMLElement']) globalThis[key] = key === 'window' ? dom.window : dom.window[key];
Object.defineProperty(globalThis, 'navigator', { value:dom.window.navigator, configurable:true });
const requests = [];
Object.defineProperty(navigator, 'geolocation', { value:{ getCurrentPosition:(success,error)=>requests.push({success,error}) }, configurable:true });
window.openModal = () => {}; window.closeModal = () => {};
window.initSimulationMap = async () => {};
window.updateTaxiPrice = () => {}; window.updateDeliveryPrice = () => {}; window.updateCargoPrice = () => {};
const point = { type:'Feature', geometry:{type:'Point',coordinates:[82.53,50.13]}, properties:{city:'Белоусовка',street:'Жукова',housenumber:'20',countrycode:'KZ'} };
let reverseResolve;
globalThis.fetch = async () => new Promise(resolve => { reverseResolve = () => resolve({ ok:true, json:async()=>({features:[point]}) }); });
const get = id => document.getElementById(id);
const select = id => document.querySelector('[data-booking-service="' + id + '"]').click();
const flush = () => new Promise(resolve=>setTimeout(resolve,0));
const position = {coords:{latitude:50.13,longitude:82.53,accuracy:20}};
get('taxiCustomerPhone').value = '+7 700 000 00 00';
const originalPhone = get('taxiCustomerPhone'), originalOtherPhone = get('passengerPhone');
initBookingScreen(); window.openModal('taxiModal');
assert.equal(get('taxiCustomerPhone'),originalPhone);
assert.equal(get('passengerPhone'),originalOtherPhone);
assert.equal(get('passengerPhone').form,get('taxiForm'));
assert.equal(originalPhone.closest('details').open,false,'Valid saved contact is compact');
assert.equal(get('taxiCustomerName').closest('details').open,false);
assert.equal(get('bookingExtras').open,false);
assert.equal(get('bookingServiceTypes').children.length,4);
assert.equal(get('bookingCarCategories').children.length,3);
assert.equal(get('bookingMoreServices').hidden,true);
assert.equal(get('bookingSubmit').textContent,'Указать маршрут');
get('bookingSubmit').click();
assert.equal(get('bookingPicker').hidden,false);
assert.equal(get('bookingPickerTitle').textContent,'Откуда');
get('bookingPickerBack').click();

// Changing a category must not invalidate geolocation; only editing the origin does.
select('minivan');
requests[0].success(position); await flush(); reverseResolve(); await flush();
assert.match(get('bookingFromValue').textContent,/Жукова/);
assert.match(get('bookingLocationStatus').textContent,/Адрес определён/);
requests[0].error(); await flush();
assert.match(get('bookingLocationStatus').textContent,/Адрес определён/,'Late location error must not erase a good address');
assert.equal(get('mapOverlayText').textContent,'Подбор водителя после заказа · Онлайн-машины · движение смоделировано');
assert.equal(window.bookingScreen.vehicleRequest().vehicleCategory,'minivan');

// Independent mode and category: a scheduled minivan remains both scheduled and minivan.
get('bookingMoreToggle').click(); assert.equal(get('bookingMoreServices').hidden,false);
select('preorder');
const date = new Date(Date.now()+86400000); date.setMinutes(date.getMinutes()-date.getTimezoneOffset());
get('taxiDateTime').value = date.toISOString().slice(0,16);
select('wagon'); assert.equal(get('taxiDateTime').disabled,false);
assert.ok(get('taxiDateTime').value);
assert.equal(window.bookingScreen.vehicleRequest().vehicleCategory,'wagon');
select('minivan'); get('bookingPassengerCount').value = '7'; get('bookingPassengerCount').dispatchEvent(new window.Event('input'));
assert.equal(window.bookingScreen.vehicleRequest().passengerCount,7);
assert.equal(get('taxiDateTime').disabled,false);
select('delivery'); assert.equal(get('bookingCarCategories').hidden,true);
assert.equal(window.bookingScreen.vehicleRequest().vehicleCategory,'sedan');
assert.equal(get('taxiDateTime').disabled,true);
select('auction'); assert.equal(get('bookingCarCategories').hidden,true);
get('bookingTaxiType').click(); assert.equal(get('bookingCarCategories').hidden,false);

// Do not let an older reverse-geocoder response replace a manually entered origin.
get('bookingLocate').click();
requests.at(-1).success({coords:{latitude:50.14,longitude:82.54,accuracy:20}}); await flush();
const lateResolve = reverseResolve;
get('bookingFrom').click(); get('bookingSearchCity').value='Глубокое'; get('bookingSearchInput').value='Центральная, 8'; get('bookingManualAddress').click();
lateResolve(); await flush();
assert.equal(get('bookingFromValue').textContent,'Центральная, 8');
assert.match(get('bookingLocationStatus').textContent,/Адрес введён вручную/);

// Required phone opens before any online handler is called.
window.repeatOrder('Жукова, 20 (Белоусовка)','Центральная, 8 (Глубокое)');
originalPhone.value = ''; originalPhone.dispatchEvent(new window.Event('input'));
assert.equal(originalPhone.closest('details').open,true);
assert.equal(get('bookingSubmit').textContent,'Указать телефон');
let sent = 0; get('taxi-online-order-button').addEventListener('click',()=>sent++);
get('bookingSubmit').click(); assert.equal(sent,0);
assert.equal(document.activeElement,originalPhone);
originalPhone.value='+7 700 000 00 00'; originalPhone.dispatchEvent(new window.Event('input'));
get('bookingExtras').open=true; get('bookingNote').value='У второго подъезда'; get('bookingNote').dispatchEvent(new window.Event('input'));
get('bookingExtras').open=false;
select('delivery'); select('taxi');
assert.equal(get('bookingNote').value,'У второго подъезда');
assert.match(get('taxiWishes').value,/У второго подъезда/);
assert.equal(get('bookingSubmit').textContent,'Заказать онлайн');
get('bookingSubmit').click(); assert.equal(sent,1);
assert.equal(get('bookingFooter').parentElement,get('bookingBody'));
assert.equal(get('bookingWhatsapp'),null);
const ids=[...document.querySelectorAll('[id]')].map(node=>node.id);
assert.equal(ids.length,new Set(ids).size);
console.log('PASS: compact contact, categories with preorder, location races, first missing field, retained wishes and online handler');
await new Promise(resolve => setTimeout(resolve,1100));
assert.equal(get('bookingSubmit').disabled,false,'Online button is released after submission');
// Price readiness gates the actual visible button; a failed route offers a call.
let fareState='pending'; window.getTaxiPriceState=()=>fareState;
get('taxiPriceEstimate').textContent='Рассчитываем стоимость…'; await flush();
assert.equal(get('bookingSubmit').disabled,true); assert.equal(get('bookingSubmit').textContent,'Рассчитываем стоимость…');
get('bookingSubmit').click();assert.equal(sent,1);
fareState='unavailable';get('taxiPriceEstimate').textContent='Уточните цену у диспетчера';await flush();
assert.equal(get('bookingSubmit').disabled,true);assert.equal(get('bookingRetryPrice').hidden,false);
assert.equal(get('bookingPriceHelp').href,get('taxi-online-dispatcher-call').href);
fareState='ready';get('taxiPriceEstimate').textContent='3500 ₸';await flush();
assert.equal(get('bookingSubmit').disabled,false);assert.equal(get('bookingPriceHelp').hidden,true);
console.log('PASS: pending/unknown prices block submit, retry is available, ready price restores submit');
get('taxi-online-order-panel').classList.remove('hidden');
get('taxi-online-order-status').textContent='Водитель подъехал'; await flush();
assert.equal(get('mapOverlayText').textContent,'Водитель подъехал · Онлайн-машины · движение смоделировано');
get('taxi-online-order-status').textContent='Поездка завершена'; await flush();
assert.equal(get('mapOverlayText').textContent,'Поездка завершена · Онлайн-машины · движение смоделировано');
get('taxi-online-order-panel').classList.add('hidden');
let deliveryState='pending', deliveryQuote=null;
window.getDeliveryPriceState=()=>deliveryState;window.getDeliveryFareForOrder=()=>deliveryQuote;
select('delivery');get('deliveryPriceEstimate').textContent='Рассчитываем стоимость…';await flush();
assert.equal(get('bookingSubmit').disabled,true);
assert.equal(get('bookingPriceCaption').textContent,'Стоимость доставки');
deliveryState='ready';deliveryQuote={amountText:'1600 ₸',reason:'×1,3 — Мало машин (модель)',calculation:'База 1200 ₸. После 3 км — 200 ₸/км.'};
get('deliveryPriceEstimate').textContent='1600 ₸ · ×1,3 — Мало машин (модель)';await flush();
assert.equal(get('bookingPrice').textContent,'1600 ₸');
assert.equal(get('bookingDeliveryCalculation').hidden,false);assert.match(get('bookingDeliveryCalculation').textContent,/200 ₸/);
assert.equal(get('bookingPriceReason').hidden,false);assert.match(get('bookingPriceReason').textContent,/Мало машин \(модель\)/);
assert.equal(get('bookingSubmit').disabled,false);
deliveryState='unavailable';deliveryQuote=null;get('deliveryPriceEstimate').textContent='Уточните цену у диспетчера';await flush();
assert.equal(get('bookingSubmit').disabled,true);assert.equal(get('bookingRetryPrice').hidden,false);
select('taxi');assert.equal(get('bookingPriceReason').hidden,true);
console.log('PASS: delivery readiness, single final fee, model reason and independent service states');
// The road route uses pickup house and every stop, excluding entrance and private notes.
select('delivery');get('bookingDetails').value='18, подъезд 2';get('bookingDetails').dispatchEvent(new window.Event('input'));
const routePoints=window.bookingScreen.deliveryRoutePoints();
assert.match(routePoints[0].address,/18/);assert.doesNotMatch(routePoints[0].address,/подъезд|У второго/);
assert.equal(routePoints[0].lat,null);assert.equal(routePoints.length,2);
// Without a pickup, the car estimate is visible but the order action asks for the pickup.
window.repeatOrder('', 'Панфилова, 8 (Белоусовка)');select('delivery');
window.getDeliveryEstimate=()=>({amountText:'2600 ₸',reason:'Без надбавки',preview:true,calculation:'От машины на карте — 10 км.'});
window.getDeliveryFareForOrder=()=>null;deliveryState='preview';
get('deliveryPriceEstimate').textContent='2600 ₸';await flush();
assert.equal(get('bookingPriceCaption').textContent,'Предварительная стоимость доставки');
assert.equal(get('bookingPrice').textContent,'2600 ₸');assert.match(get('bookingPriceReason').textContent,/Укажите место получения/);
assert.equal(get('bookingSubmit').textContent,'Указать место получения');
let deliverySent=0;get('delivery-online-order-button').addEventListener('click',()=>deliverySent++);
get('bookingSubmit').click();assert.equal(deliverySent,0);assert.equal(get('bookingPicker').hidden,false);
assert.equal(get('bookingPickerTitle').textContent,'Откуда');
assert.match(get('bookingStatus').textContent,/Укажите адрес/);
get('bookingSearchCity').value='Белоусовка';get('bookingSearchInput').value='Жукова, 20';get('bookingManualAddress').click();
assert.equal(get('bookingFromValue').textContent,'Жукова, 20');
assert.equal(get('bookingStatus').textContent,'','Selecting the missing pickup clears the previous validation message');
console.log('PASS: route point house, private entrance exclusion, preliminary car estimate and required pickup');
// Generic shop text and the dedicated choice do not require a fabricated street.
get('bookingFrom').click();assert.equal(get('bookingPickerAnyStore').hidden,false);
get('bookingSearchInput').value='магазин';get('bookingManualAddress').click();
assert.equal(get('bookingAnyStore').getAttribute('aria-pressed'),'true');
assert.match(get('bookingFromValue').textContent,/Любой магазин/);
assert.equal(get('deliveryStore').value,'Любой магазин — выбирает водитель');
assert.equal(get('bookingDetails').hidden,true);assert.equal(get('bookingSwap').hidden,true);
select('taxi');assert.equal(get('bookingAnyStore').hidden,true);
assert.equal(get('taxiFrom').value,'','Any store must not become a taxi pickup');
assert.equal(get('bookingDetails').hidden,false);assert.equal(get('bookingSwap').hidden,false);
select('delivery');get('bookingAnyStore').click();
assert.equal(get('bookingPicker').hidden,true);assert.equal(get('bookingStatus').textContent,'');
assert.equal(window.bookingScreen.deliveryRoutePoints()[0].address,'Любой магазин');
deliveryState='ready';deliveryQuote={priceAmount:3400,amountText:'3400 ₸',anyStore:true,preview:false,reason:'×1,3 — Мало машин (модель)',calculation:'От случайной машины на карте — 10 км.'};
window.getDeliveryEstimate=()=>deliveryQuote;window.getDeliveryFareForOrder=()=>deliveryQuote;
get('deliveryPriceEstimate').textContent='3400 ₸';get('deliveryItems').value='Хлеб, молоко';
get('deliveryCustomerPhone').value='+7 700 000 00 00';get('deliveryCustomerPhone').dispatchEvent(new window.Event('input'));await flush();
assert.equal(get('bookingPriceCaption').textContent,'Стоимость доставки');assert.match(get('bookingPriceReason').textContent,/случайной машины/);
assert.match(get('bookingSubmit').textContent,/Заказать за/);assert.equal(get('bookingSubmit').disabled,false);
get('bookingSubmit').click();assert.equal(deliverySent,1,'A priced any-store request reaches the order handler without a street pickup');
console.log('PASS: generic shop, explicit any-store choice, clean service switch and ordering without an exact store');
await new Promise(resolve => setTimeout(resolve,1100));
window.customerPricingReady=true;window.customerPriceSettings={enabled:true,quickPercentages:[10,20,30],minimumIncrease:1,maximumPrice:1000000,taxiMinimum:800,deliveryMinimum:1200};
window.dispatchEvent(new window.Event('customer-pricing-ready'));await flush();
const offerHost=get('bookingCustomerPrice');assert.equal(offerHost.hidden,false);
offerHost.querySelector('.customer-price-toggle').click();
offerHost.querySelectorAll('.customer-price-quick button')[1].click();
assert.equal(window.getCustomerPriceOffer('delivery'),4080);assert.match(get('bookingSubmit').textContent,/4\s080/);
get('bookingNote').value='Тест';get('bookingNote').dispatchEvent(new window.Event('input'));await flush();assert.equal(window.getCustomerPriceOffer('delivery'),4080,'Note editing does not erase the offer');
offerHost.querySelector('input').value='3000';offerHost.querySelector('input').dispatchEvent(new window.Event('input'));assert.equal(get('bookingSubmit').disabled,false);
get('bookingSubmit').click();assert.match(get('bookingStatus').textContent,/стоимость/);
offerHost.querySelector('.customer-price-reset').click();assert.equal(window.getCustomerPriceOffer('delivery'),null);
deliveryState='unavailable';deliveryQuote=null;get('deliveryPriceEstimate').textContent='Не удалось рассчитать стоимость';await flush();
assert.equal(offerHost.hidden,false);offerHost.querySelector('.customer-price-toggle').click();
offerHost.querySelector('input').value='1500';offerHost.querySelector('input').dispatchEvent(new window.Event('input'));assert.equal(get('bookingSubmit').disabled,false);assert.match(get('bookingSubmit').textContent,/1\s500/);
console.log('PASS: optional increases, lower price rejection, reset, preserved notes and unavailable calculation fallback');

// Offer selection is independent of a pending/failed/retried route, including a late higher quote.
deliveryState='pending';deliveryQuote=null;get('deliveryPriceEstimate').textContent='Повторный расчёт…';await flush();
assert.equal(offerHost.querySelector('input').value,'1500');assert.equal(get('bookingSubmit').disabled,false);
deliveryState='ready';deliveryQuote={priceAmount:7000,amountText:'7000 ₸'};get('deliveryPriceEstimate').textContent='7000 ₸';await flush();
assert.equal(window.getCustomerPriceSelection('delivery').calculatedPrice,null);
assert.equal(window.getCustomerPriceOffer('delivery'),1500);assert.match(get('bookingSubmit').textContent,/1\s500/);
let recalculations=0;window.updateDeliveryPrice=()=>recalculations++;
get('bookingSubmit').click();assert.equal(deliverySent,2);assert.equal(recalculations,0,'Submitting does not restart pricing');
await new Promise(resolve=>setTimeout(resolve,1100));
// Text need not resolve to a directory entry, and an absent locality stays absent.
select('taxi');fareState='pending';get('taxiPriceEstimate').textContent='Расчёт…';
get('bookingFrom').click();get('bookingSearchCity').value='';get('bookingSearchInput').value='Чапаева көшесі, у поворота';get('bookingManualAddress').click();
assert.equal(get('bookingPicker').hidden,true);
assert.equal(window.bookingScreen.orderRoute('taxi').from.city,'');
assert.equal(get('taxiFrom').value,'Чапаева көшесі, у поворота');
assert.equal(get('bookingCustomerPrice').hidden,false);
const taxiOffer=get('bookingCustomerPrice').querySelector('input');
get('bookingSubmit').click();assert.equal(sent,1);assert.match(get('bookingStatus').textContent,/Укажите желаемую стоимость/);
for (const amount of ['', '0', '-100', '799', '800.5', '1000001']) {
  taxiOffer.value=amount;taxiOffer.dispatchEvent(new window.Event('input'));get('bookingSubmit').click();assert.equal(sent,1,`Invalid ${amount} must not submit`);
}
taxiOffer.value='1701';taxiOffer.dispatchEvent(new window.Event('input'));get('bookingSubmit').click();assert.equal(sent,2);
await new Promise(resolve=>setTimeout(resolve,1100));
// A map point is accepted after the bounded lookup even when the directory never answers.
const center={lat:50.876543,lng:82.654321};
const marker={addTo(){return this;},setLatLng(){return this;}};
window.L={marker:()=>marker,divIcon:()=>({}),geoJSON:()=>({addTo(){return this;},getBounds:()=>[]})};
window.simMap={getCenter:()=>center,invalidateSize(){},setView(){},removeLayer(){},fitBounds(){},off(){},on(){}};
get('bookingTo').click();get('bookingOnMap').click();get('bookingPickConfirm').click();
assert.equal(get('bookingPickConfirm').disabled,true);
await new Promise(resolve=>setTimeout(resolve,2600));
const mapDestination=window.bookingScreen.orderRoute('taxi').to;
assert.equal(mapDestination.city,'');assert.equal(mapDestination.lat,center.lat);assert.equal(mapDestination.lon,center.lng);
assert.match(get('bookingToValue').textContent,/Точка на карте: 50.87654, 82.65432/);
assert.equal(get('bookingPicker').hidden,true);assert.equal(get('bookingPickConfirm').disabled,false);
assert.equal(window.bookingScreen.orderRoute('taxi').coordinates.at(-1).lat,center.lat);
console.log('PASS: pending manual offers, late quotes, no submit recalculation, unknown Kazakh address, invalid money and map lookup timeout');
dom.window.close();
