import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import { initBookingScreen } from '../../booking-screen.js';
import { initClientHome } from '../../client-home.js';
import { priceSettings } from '../../customer-pricing.js';
import { createVehicleControls } from '../../vehicle-category-controls.js';
import { createSoberExpenseEditor } from '../../sober-dispatch.js';
const dom=new JSDOM(await readFile(new URL('../../index.html',import.meta.url),'utf8'),{url:'https://example.test/',pretendToBeVisual:true});
for (const key of ['window','document','MutationObserver','Option','HTMLElement']) globalThis[key]=key==='window'?dom.window:dom.window[key];
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition:()=>{}},configurable:true});
globalThis.fetch=async()=>({ok:true,json:async()=>({features:[]})});
window.openModal=()=>{};window.closeModal=()=>{};window.initSimulationMap=async()=>{};window.scrollTo=()=>{};
window.HTMLElement.prototype.scrollIntoView=()=>{};
window.updateTaxiPrice=()=>{};window.updateDeliveryPrice=()=>{};window.updateCargoPrice=()=>{};window.updateSoberPrice=()=>{};
window.customerPricingReady=true;window.customerPriceSettings=priceSettings();
let quote=null;window.getSoberFareForOrder=()=>quote;window.getSoberExpenses=()=>quote;window.getSoberPriceState=()=>quote?'ready':'pending';
const get=id=>document.getElementById(id),flush=()=>new Promise(resolve=>setTimeout(resolve,0));
initBookingScreen();initClientHome();
window.repeatOrder('Чапаева көшесі (Белоусовка)','Полевой поворот (Глубокое)');
document.querySelector('[data-booking-service="soberDriver"]').click();
assert.equal(get('bookingSubmit').disabled,true,'Backend must be deployed before online orders open');
window.soberBookingReady=true;window.dispatchEvent(new window.Event('sober-booking-ready'));await flush();
assert.equal(get('bookingSubmit').disabled,false,'Pending geocoding cannot block manual price');
get('soberDriverCustomerPhone').value='+77000000000';get('soberDriverCustomerPhone').dispatchEvent(new window.Event('input'));
get('soberDriverCarModel').value='Toyota';get('soberDriverTransmission').value='manual';
let sent=0;get('soberDriver-online-order-button').addEventListener('click',()=>sent++);
get('bookingSubmit').click();assert.equal(sent,0);assert.equal(document.activeElement,get('booking-offer-amount'));
get('booking-offer-amount').value='5000';get('booking-offer-amount').dispatchEvent(new window.Event('input'));
assert.equal(get('bookingSubmit').textContent,'Заказать за 5 000 ₸');
quote={priceAmount:8000,pickupAmount:1000,returnAmount:2000};get('soberDriverPriceEstimate').textContent='8000 ₸';await flush();
assert.equal(get('booking-offer-amount').value,'5000');assert.equal(window.getCustomerPriceSelection('soberDriver').calculatedPrice,null);
get('bookingSubmit').click();await flush();assert.equal(sent,1);
assert.match(get('bookingDeliveryCalculation').textContent,/Подача из Белоусовки/);
get('soberDriver-online-order-panel').classList.remove('hidden');get('soberDriver-online-order-status').textContent='Водитель подъехал';await flush();
assert.equal(get('bookingFooter').hidden,true);assert.match(document.querySelector('[data-home-current]').textContent,/Водитель подъехал/);
const controls=createVehicleControls({soberDriverEnabled:true});assert.equal(controls.read().soberDriverEnabled,true);controls.reset();assert.equal(controls.read().soberDriverEnabled,false);
let saved;const editor=createSoberExpenseEditor({priceAmount:5000,soberFare:{pickupAmount:null,returnAmount:null}},async value=>{saved=value;});document.body.append(editor);
const fields=editor.querySelectorAll('input');fields[0].value='1000';fields[1].value='1500';editor.dispatchEvent(new window.Event('submit',{cancelable:true}));await flush();
assert.deepEqual(saved,{pickupAmount:1000,returnAmount:1500});assert.match(editor.textContent,/Расходы подтверждены/);
console.log('PASS: sober backend gate, manual offer during and after delayed calculation, car fields, submit, current order, opt-in and expense editor');
await new Promise(resolve=>setTimeout(resolve,1100));dom.window.close();
